connecteddin/connectedin/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('perfis.urls')), 
	url(r'^', include('usuarios.urls'))
)

connecteddin/perfis/urls.py
from django.conf.urls import patterns, url
#from perfis import views

urlpatterns = patterns('',
	url(r'^$', 'perfis.views.index', name="index"),
	#url(r'^$', index, name='index')
	url(r'^perfis/(?P<perfil_id>\d+)$', 'perfis.views.exibir', name="exibir"),
	url(r'^perfis/(?P<perfil_id>\d+)/convidar$', 'perfis.views.convidar', name="convidar"),
	url(r'^convite/(?P<convite_id>\d+)/aceitar', 'perfis.views.aceitar', name='aceitar')
)

connecteddin/usuarios/urls.py
from django.conf.urls import patterns, url
from views import RegistrarUsuariosView

urlpatterns = patterns('',
    url(r'^registrar/$', RegistrarUsuariosView.as_view(), name="registrar")
    )

connecteddin/perfis/models.py
# Create your models here.

from django.db import models

class Perfil(models.Model):
   nome = models.CharField(max_length=255, null=False)
   email = models.CharField(max_length=255, null=False)
   telefone = models.CharField(max_length=15, null=False)
   nome_empresa = models.CharField(max_length=255, null=False)      
   contatos = models.ManyToManyField('self')

   def convidar(self, perfil_convidado):
        Convite(solicitante=self, convidado=perfil_convidado).save()

class Convite(models.Model):
    solicitante = models.ForeignKey(Perfil, related_name='convites_feitos')
    convidado = models.ForeignKey(Perfil, related_name='convites_recebidos')

    def aceitar(self):
        self.convidado.contatos.add(self.solicitante)
        self.solicitante.contatos.add(self.convidado)
        self.delete()

connecteddin/usuarios/models.py
from django.db import models

# Create your models here.

connecteddin/usuarios/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistraUsuarioForm(forms.Form):

    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    fone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(RegistraUsuarioForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados')
            valid = False

        user_exists =  User.objects.filter(username=self.data['nome']).exists()

        if user_exists:
            self.adiciona_erro('Usuario ja existente')
            valid = False
        
        return valid

    def adiciona_erro(self, messsage):
        erros = self._erros.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        error.append(messsage)

connecteddin/perfis/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from perfis.models import Perfil, Convite

def index(request):
	#return render(request, 'index.html')
	return render(request, 'index.html', {"perfis":Perfil.objects.all(), 'perfil_logado' : get_perfil_logado(request)})

def exibir(request, perfil_id):
	print 'ID do perfil recebido: %s' % (perfil_id)

	perfil = Perfil.objects.get(id=perfil_id)

	perfil_logado = get_perfil_logado(request)
	ja_eh_contato = perfil in perfil_logado.contatos.all()

	return render(request, 'perfil.html', {"perfil":perfil, "ja_eh_contato": ja_eh_contato})

def convidar(request, perfil_id):
	perfil_a_convidar = Perfil.objects.get(id=perfil_id)
	perfil_logado = get_perfil_logado(request)
	perfil_logado.convidar(perfil_a_convidar)
	return redirect('index')

def aceitar(request, convite_id):
	convite = Convite.objects.get(id=convite_id)
	convite.aceitar()
	return redirect('index')

def get_perfil_logado(request):
	return Perfil.objects.get(id=1)

connecteddin/usuarios/views.py
from django.shortcuts import render
from django.views.generic.base import View

# Create your views here.
class RegistrarUsuariosView(View):
    
    template_name = "registrar.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        return render(request, self.template_name)

connecteddin/perfis/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static "styles/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "styles/main.css" %}">
    <title>ConnectedIn</title>
</head>
<body>
    <div class="container">
        <div class="header">
                <ul class="nav nav-pills pull-right">
                    <li><a href="{% url 'index' %}">{{perfil_logado.nome}}</a></li>
                    <li><a href="/logout/">Logout</a></li>
                </ul>
                <h3 class="text-muted">ConnectedIn</h3>
            </div>
            <div class="row content">
                {% block body%}
                {% endblock %}
            </div>
    </div>
</body>
</html>

connecteddin/perfis/templates/index.html
{% extends "base.html"%}
{% block body%}
<div class="col-lg-12">
	<div class="panel panel-default">
		<div class="panel-heading">
			<strong>Todos os perfis</strong>
		</div>
			{% if perfis%}
			<ul>
				{% for perfil in perfis %}	
					<li>
							<a href="{% url 'exibir' perfil.id %}">
									{{ perfil.nome | upper}}
							</a> 
						/ {{ perfil.email }}
					</li>
				{% endfor %}
			</ul>
			{% else %}
				<p>Nenhum perfil encontrado</p>
			{% endif %}
	</div>

	<div class="panel panel-default">
		<!--Não pode haver espaço na clausula with -->
		{% with total_de_convites=perfil_logado.convites_recebidos.count %}
			{% if total_de_convites %}
				<div class="panel-heading">
					<strong>Você tem {{ total_de_convites }} convite{{ total_de_convites | pluralize}} aguardando aprovação</strong>
				</div>
				<ul class="list-group">
					{% for convite in perfil_logado.convites_recebidos.all %}
						<li class="list-group-item">
							{{ convite.solicitante.nome }}
							<a href="{% url 'aceitar' convite.id%}" class="pull-right">aceitar</a>
						</li>
					{% endfor%}
				</ul>
			{% else %}
				<div class="panel-body">
					<p>Nenhum convite recebido :(</p>
				</div>

			{% endif%}
		{% endwith%}
	</div>

	<div class="panel panel-default">
		<!--Não pode haver espaço na clausula with -->
		{% with total_de_contatos=perfil_logado.contatos.count %}
			{% if total_de_contatos %}
				<div class="panel-heading">
					<strong>Você tem {{ total_de_contatos }} contatos{{ total_de_contatos | pluralize}} </strong>
				</div>
				<ul class="list-group">
					{% for contato in perfil_logado.contatos.all %}
						<li class="list-group-item">
							<a href="{% url 'exibir' contato.id %}">{{ contato.nome }}</a>
						</li>
					{% endfor%}
				</ul>
			{% else %}
				<div class="panel-body">
					<p>Voce nao possui contatos no momento :(</p>
				</div>

			{% endif%}
		{% endwith%}

	</div>
</div>
{% endblock%}

connecteddin/perfis/templates/perfil.html
<!-- connectedin/perfis/templates/index.html -->
{% extends "base.html"%}
{% block body%}
<div class="row">
  <div class="col-lg-12">
    <h2 style="margin-top:0">{{ perfil.nome }}</h2>
    <address>
      <strong>{{ perfil.nome_empresa }}</strong><br>
      <abbr title="Telefone">Tel:</abbr> {{ perfil.telefone }} <br>
      <a href="mailto: {{ perfil.email }}"> {{ perfil.email }}</a>
    </address>

    {% if ja_eh_contato%}
      <div class="well well-sm">Voces estao conectados!</div>
    {% else%}
      <a href="{% url 'convidar' perfil.id %}">convidar</a>
    {% endif%}

   
  </div>
</div>

{% endblock%}

connecteddin/usuarios/templates/base_usuario.html
{% load staticfiles%}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ConnectedIn</title>
    <link rel="stylesheet" href="{% static  "styles/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static  "styles/signin.css" %}">
</head>
<body>
    <div class="container">
        {% block body%}
        {% endblock%}
    </div>
    
</body>
</html>

connecteddin/usuarios/templates/registrar.html
{% extends "base_usuario.html"%}
{% block body%}
    <form class="form-signin" action="{% url 'registrar' %}" method="post">
        {% csrf_token%} <! Cross Site Request Forgery previne Falsificação de solicitação entre sites>
        <h2 class="form-signin-heading">Crie seu usuario</h2>

        <input id="id_email" name="email" type="text"
                class="form-control" placeholder="Email*" required>
                
        <input id="id_nome" name="nome" type="text" 
                class="form-control" placeholder="Nome*" required>

        <input id="id_senha" name="senha" type="password" 
                class="form-control" placeholder="Senha*" required>
        
        <input id="id_fone" name="fone" type="text" 
                class="form-control" placeholder="Fone" >

        <input id="id_empresa" name="empresa" type="text" 
                class="form-control" placeholder="Empresa" >

        <hr/>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Registrar</button>

    </form>
{% endblock%}